# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xcku5p-ffvb676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.cache/wt [current_project]
set_property parent.project_path D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu116:part0:1.2 [current_project]
set_property ip_output_repo d:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/ArithmeticUnit.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/ArithmeticUnitI.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/Buf.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/DataMemory.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/Decoder.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/Execute.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/FullAdder.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/FunctionalUnit.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/InstructionDecode.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/InstructionFetch.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/InstructionMemory.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/LogicUnit.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/LogicUnitI.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/Memory.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/RegisterFile.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/RegisterN.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/Shifter.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/WriteBack.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/Zero.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/branchcontrol.vhd
  D:/User/Desktop/aac-proj/Proj1/Lab1/Lab1.srcs/sources_1/imports/design/SingleCycle.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top SingleCycle -part xcku5p-ffvb676-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SingleCycle.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SingleCycle_utilization_synth.rpt -pb SingleCycle_utilization_synth.pb"
